[package]
name = "rust_clean_architecture_derive"
version = "0.1.0"
authors = ["junmoka <jun_moka@spiriquor.com>"]
edition = "2018"

[dependencies]
syn = "0.15.26"
quote = "0.6.11"
proc-macro2 = "0.4.27"
case = "1.0.0"

[lib]
proc-macro = true